name: data-analysis-course
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - snakemake-minimal
  - pandas
  - codecarbon
  - matplotlib
  - xsv=0.13
  - bowtie2
  - samtools
  - curl
  - pip
